/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lbpbtxfvqauzopqpltqs"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxicGJ0eGZ2cWF1em9wcXBsdHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3NzYzNDIsImV4cCI6MjA3ODM1MjM0Mn0.OKZqDIuWXERxKT3-S-IOEhoxPA8ZmMC3KTdb3xSgTaQ"